import type { JsonObject } from "./schema";

export type SeedWorkflowCatalogEntry = {
  workflowIdKey: string;
  runIdKey: string;
  stepIdKey: string;
  key: string;
  name: string;
  purpose: string;
  domain: string;
  states: JsonObject;
  transitions: JsonObject;
  objects: JsonObject;
  approvals: JsonObject;
  evidence: JsonObject;
  tests: JsonObject;
  objectIdKey?: string;
  workerIdKey?: string;
  runState: string;
  runData: JsonObject;
  blockers: string[];
  metrics: JsonObject;
  stepName: string;
  stepOutput: JsonObject;
};

export const extendedWorkflowCatalog: SeedWorkflowCatalogEntry[] = [
  {
    workflowIdKey: "workflowOpenNewState",
    runIdKey: "runOpenNewState",
    stepIdKey: "stepOpenNewState",
    key: "open_new_state",
    name: "Open new state",
    purpose: "Prepare registrations, tax accounts, reporting paths, and payroll readiness for a new operating state.",
    domain: "entity",
    states: { order: ["draft", "facts_required", "rule_review", "registration_ready", "payroll_ready"] },
    transitions: {
      draft: ["facts_required"],
      facts_required: ["rule_review"],
      rule_review: ["registration_ready", "blocked"],
      registration_ready: ["payroll_ready"],
    },
    objects: { required: ["work_location", "state_registration", "tax_account", "filing_requirement"] },
    approvals: { required: ["state_registration_review", "payroll_nexus_review"] },
    evidence: { packet: "state_readiness_packet" },
    tests: { required: ["nexus_facts_present", "registration_path_known", "payroll_readiness_blockers"] },
    objectIdKey: "workLocationObject",
    runState: "rule_review",
    runData: { state: "NY", registration: "draft_only", payrollReadiness: false },
    blockers: ["agency_account_required", "withholding_account_not_verified"],
    metrics: { readiness: 0.34 },
    stepName: "Open new state seeded rule review",
    stepOutput: { blockers: ["agency_account_required", "withholding_account_not_verified"] },
  },
  {
    workflowIdKey: "workflowCompensationChange",
    runIdKey: "runCompensationChange",
    stepIdKey: "stepCompensationChange",
    key: "compensation_change",
    name: "Change compensation",
    purpose: "Review wage or salary changes with approval, effective dating, retro analysis, and payroll impact evidence.",
    domain: "workforce",
    states: { order: ["draft", "impact_review", "approval_pending", "payroll_update_ready", "closed"] },
    transitions: {
      draft: ["impact_review"],
      impact_review: ["approval_pending", "blocked"],
      approval_pending: ["payroll_update_ready", "rejected"],
      payroll_update_ready: ["closed"],
    },
    objects: { required: ["employment", "compensation_agreement", "payroll_run"] },
    approvals: { required: ["manager_compensation_approval"], states: { approval_pending: ["manager_compensation_approval"] } },
    evidence: { packet: "compensation_change_packet" },
    tests: { required: ["effective_date_present", "retro_pay_analysis", "payroll_impact_report"] },
    objectIdKey: "employmentObject",
    runState: "approval_pending",
    runData: { employmentId: "seed-employment", compensationAgreementId: "seed-compensation-agreement" },
    blockers: ["manager_compensation_approval_required"],
    metrics: { readiness: 0.62 },
    stepName: "Compensation change seeded approval pending",
    stepOutput: { blockers: ["manager_compensation_approval_required"] },
  },
  {
    workflowIdKey: "workflowLocationChange",
    runIdKey: "runLocationChange",
    stepIdKey: "stepLocationChange",
    key: "location_change",
    name: "Change work location",
    purpose: "Evaluate work location, tax nexus, withholding, benefits, and labor-rule impact before payroll changes.",
    domain: "workforce",
    states: { order: ["draft", "tax_review", "benefits_review", "approval_pending", "payroll_update_ready"] },
    transitions: {
      draft: ["tax_review"],
      tax_review: ["benefits_review", "blocked"],
      benefits_review: ["approval_pending"],
      approval_pending: ["payroll_update_ready", "rejected"],
    },
    objects: { required: ["person", "employment", "work_location", "tax_nexus_profile"] },
    approvals: { required: ["location_change_approval"], states: { approval_pending: ["location_change_approval"] } },
    evidence: { packet: "location_change_packet" },
    tests: { required: ["work_state_present", "withholding_impact", "labor_rule_review"] },
    objectIdKey: "workLocationObject",
    runState: "tax_review",
    runData: { workLocationObjectId: "seed-work-location", taxNexusReview: true },
    blockers: ["local_tax_rule_review_required"],
    metrics: { readiness: 0.46 },
    stepName: "Location change seeded tax review",
    stepOutput: { blockers: ["local_tax_rule_review_required"] },
  },
  {
    workflowIdKey: "workflowRunPayroll",
    runIdKey: "runRunPayroll",
    stepIdKey: "stepRunPayroll",
    key: "run_payroll",
    name: "Run payroll",
    purpose: "Lock payroll source data, approve deterministic calculations, prepare funding, and reconcile pay liabilities.",
    domain: "payroll",
    states: { order: ["draft", "source_data_locked", "calculating", "awaiting_approval", "payment_prepared", "reconciled"] },
    transitions: {
      draft: ["source_data_locked"],
      source_data_locked: ["calculating"],
      calculating: ["awaiting_approval", "blocked"],
      awaiting_approval: ["payment_prepared", "rejected"],
      payment_prepared: ["reconciled"],
    },
    objects: { required: ["pay_schedule", "payroll_run", "pay_statement", "payment_instruction"] },
    approvals: { required: ["payroll_approval", "dual_control_for_funding"], states: { awaiting_approval: ["payroll_approval", "dual_control_for_funding"] } },
    evidence: { packet: "payroll_packet" },
    tests: { required: ["deterministic_calculation", "variance_report", "funding_blocked_until_approval"] },
    objectIdKey: "payrollObject",
    runState: "source_data_locked",
    runData: { payrollRunId: "seed-payroll-preview", sourceDataLocked: true },
    blockers: ["payroll_calculation_not_final"],
    metrics: { gross_cents: 336000, net_cents: 248640 },
    stepName: "Run payroll seeded source data locked",
    stepOutput: { sourceDataLocked: true, externalSubmission: "blocked" },
  },
  {
    workflowIdKey: "workflowOffCyclePayroll",
    runIdKey: "runOffCyclePayroll",
    stepIdKey: "stepOffCyclePayroll",
    key: "off_cycle_payroll",
    name: "Off-cycle payroll",
    purpose: "Handle corrections, bonuses, final pay, or missed earnings with calculation trace and approval evidence.",
    domain: "payroll",
    states: { order: ["draft", "reason_review", "calculation_trace_ready", "approval_pending", "payment_prepared", "closed"] },
    transitions: {
      draft: ["reason_review"],
      reason_review: ["calculation_trace_ready", "blocked"],
      calculation_trace_ready: ["approval_pending"],
      approval_pending: ["payment_prepared", "rejected"],
      payment_prepared: ["closed"],
    },
    objects: { required: ["payroll_run", "payment_instruction", "compensation_agreement"] },
    approvals: { required: ["off_cycle_payroll_approval"], states: { approval_pending: ["off_cycle_payroll_approval"] } },
    evidence: { packet: "off_cycle_packet" },
    tests: { required: ["reason_present", "tax_treatment_trace", "correction_link"] },
    objectIdKey: "payrollObject",
    runState: "reason_review",
    runData: { reason: "correction_or_final_pay", paymentDraft: "blocked" },
    blockers: ["earning_tax_treatment_required"],
    metrics: { readiness: 0.28 },
    stepName: "Off-cycle payroll seeded reason review",
    stepOutput: { blockers: ["earning_tax_treatment_required"] },
  },
  {
    workflowIdKey: "workflowQuarterClose",
    runIdKey: "runQuarterClose",
    stepIdKey: "stepQuarterClose",
    key: "quarter_close",
    name: "Quarter close",
    purpose: "Reconcile payroll aggregates, tax liabilities, deposits, filings, and quarter-end evidence.",
    domain: "filings",
    states: { order: ["draft", "reconciliation", "filing_drafts_ready", "approval_pending", "receipt_reconciliation", "closed"] },
    transitions: {
      draft: ["reconciliation"],
      reconciliation: ["filing_drafts_ready", "blocked"],
      filing_drafts_ready: ["approval_pending"],
      approval_pending: ["receipt_reconciliation", "rejected"],
      receipt_reconciliation: ["closed"],
    },
    objects: { required: ["payroll_run", "filing_requirement", "filing_draft", "obligation"] },
    approvals: { required: ["quarter_close_approval"], states: { approval_pending: ["quarter_close_approval"] } },
    evidence: { packet: "quarter_close_packet" },
    tests: { required: ["liability_reconciliation", "deposit_trace", "filing_draft_present"] },
    objectIdKey: "filingObject",
    runState: "reconciliation",
    runData: { filingDraftId: "seed-filing-draft", period: "quarter" },
    blockers: ["deposit_reconciliation_required"],
    metrics: { readiness: 0.4 },
    stepName: "Quarter close seeded reconciliation",
    stepOutput: { blockers: ["deposit_reconciliation_required"] },
  },
  {
    workflowIdKey: "workflowFilingDraft",
    runIdKey: "runFilingDraft",
    stepIdKey: "stepFilingDraft",
    key: "filing_draft",
    name: "Filing draft",
    purpose: "Prepare a filing draft from requirements, source facts, validation results, approvals, and receipt-ready evidence.",
    domain: "filings",
    states: { order: ["draft", "source_data_review", "validation", "review_ready", "approval_pending", "ready_to_file"] },
    transitions: {
      draft: ["source_data_review"],
      source_data_review: ["validation", "blocked"],
      validation: ["review_ready", "blocked"],
      review_ready: ["approval_pending"],
      approval_pending: ["ready_to_file", "rejected"],
    },
    objects: { required: ["legal_entity", "filing_requirement", "filing_draft", "obligation"] },
    approvals: { required: ["filing_draft_approval"], states: { approval_pending: ["filing_draft_approval"] } },
    evidence: { packet: "filing_draft_packet" },
    tests: { required: ["source_data_present", "validation_trace", "submission_blocked_until_approval"] },
    objectIdKey: "filingObject",
    runState: "review_ready",
    runData: { filingRequirementId: "seed-filing-requirement", filingDraftId: "seed-filing-draft", submission: "blocked" },
    blockers: ["filing_draft_approval_required"],
    metrics: { readiness: 0.64 },
    stepName: "Filing draft seeded review ready",
    stepOutput: { blockers: ["filing_draft_approval_required"], submission: "blocked" },
  },
  {
    workflowIdKey: "workflowYearEnd",
    runIdKey: "runYearEnd",
    stepIdKey: "stepYearEnd",
    key: "year_end",
    name: "Year-end",
    purpose: "Prepare annual worker, contractor, payroll, and state reconciliation records with correction paths.",
    domain: "filings",
    states: { order: ["draft", "source_data_required", "forms_prepared", "approval_pending", "copies_ready", "closed"] },
    transitions: {
      draft: ["source_data_required"],
      source_data_required: ["forms_prepared", "blocked"],
      forms_prepared: ["approval_pending"],
      approval_pending: ["copies_ready", "rejected"],
      copies_ready: ["closed"],
    },
    objects: { required: ["person", "employment", "filing_requirement", "filing_draft"] },
    approvals: { required: ["year_end_filing_approval"], states: { approval_pending: ["year_end_filing_approval"] } },
    evidence: { packet: "year_end_packet" },
    tests: { required: ["worker_copy_set", "contractor_copy_set", "state_reconciliation"] },
    objectIdKey: "filingObject",
    runState: "source_data_required",
    runData: { forms: ["w2", "1099"], corrections: "supported" },
    blockers: ["worker_copy_data_required"],
    metrics: { readiness: 0.22 },
    stepName: "Year-end seeded source data required",
    stepOutput: { blockers: ["worker_copy_data_required"] },
  },
  {
    workflowIdKey: "workflowLeave",
    runIdKey: "runLeave",
    stepIdKey: "stepLeave",
    key: "leave",
    name: "Leave",
    purpose: "Track leave eligibility, notices, certification, benefits continuation, payroll handling, and return-to-work state.",
    domain: "workforce",
    states: { order: ["requested", "eligibility_review", "certification_pending", "approved", "active_leave", "return_to_work"] },
    transitions: {
      requested: ["eligibility_review"],
      eligibility_review: ["certification_pending", "approved", "blocked"],
      certification_pending: ["approved", "blocked"],
      approved: ["active_leave"],
      active_leave: ["return_to_work"],
    },
    objects: { required: ["person", "employment", "document", "payroll_run"] },
    approvals: { required: ["leave_eligibility_review"] },
    evidence: { packet: "leave_packet" },
    tests: { required: ["eligibility_facts", "notice_packet", "payroll_handling"] },
    objectIdKey: "employmentObject",
    runState: "eligibility_review",
    runData: { leaveType: "protected_leave_review", payrollImpact: true },
    blockers: ["eligibility_facts_required"],
    metrics: { readiness: 0.35 },
    stepName: "Leave seeded eligibility review",
    stepOutput: { blockers: ["eligibility_facts_required"] },
  },
  {
    workflowIdKey: "workflowInjuryIncident",
    runIdKey: "runInjuryIncident",
    stepIdKey: "stepInjuryIncident",
    key: "injury_incident",
    name: "Injury or incident",
    purpose: "Capture incident facts, recordability review, documents, workers' compensation path, and required forms.",
    domain: "compliance",
    states: { order: ["reported", "facts_required", "recordability_review", "forms_prepared", "approval_pending", "closed"] },
    transitions: {
      reported: ["facts_required"],
      facts_required: ["recordability_review"],
      recordability_review: ["forms_prepared", "blocked"],
      forms_prepared: ["approval_pending"],
      approval_pending: ["closed", "rejected"],
    },
    objects: { required: ["person", "work_location", "document", "obligation"] },
    approvals: { required: ["incident_recordability_review"], states: { approval_pending: ["incident_recordability_review"] } },
    evidence: { packet: "incident_packet" },
    tests: { required: ["witness_facts", "photo_or_doc_refs", "recordability_rationale"] },
    objectIdKey: "workLocationObject",
    runState: "recordability_review",
    runData: { incidentReport: "draft", recordability: "review_required" },
    blockers: ["witness_facts_required"],
    metrics: { readiness: 0.3 },
    stepName: "Incident seeded recordability review",
    stepOutput: { blockers: ["witness_facts_required"] },
  },
  {
    workflowIdKey: "workflowBenefitsRenewal",
    runIdKey: "runBenefitsRenewal",
    stepIdKey: "stepBenefitsRenewal",
    key: "benefits_renewal",
    name: "Benefits renewal",
    purpose: "Coordinate plan year, eligibility, elections, dependent changes, carrier sync, deductions, and notices.",
    domain: "workforce",
    states: { order: ["draft", "plan_review", "eligibility_review", "elections_pending", "deductions_ready", "closed"] },
    transitions: {
      draft: ["plan_review"],
      plan_review: ["eligibility_review", "blocked"],
      eligibility_review: ["elections_pending"],
      elections_pending: ["deductions_ready", "blocked"],
      deductions_ready: ["closed"],
    },
    objects: { required: ["person", "employment", "compensation_agreement", "document"] },
    approvals: { required: ["benefits_plan_review"] },
    evidence: { packet: "benefits_packet" },
    tests: { required: ["eligibility_snapshot", "deduction_mapping", "notice_packet"] },
    objectIdKey: "employmentObject",
    runState: "plan_review",
    runData: { planYear: "next", carrierSync: "dry_run" },
    blockers: ["plan_selection_required"],
    metrics: { readiness: 0.33 },
    stepName: "Benefits renewal seeded plan review",
    stepOutput: { blockers: ["plan_selection_required"] },
  },
  {
    workflowIdKey: "workflowAgencyNotice",
    runIdKey: "runAgencyNotice",
    stepIdKey: "stepAgencyNotice",
    key: "agency_notice",
    name: "Agency notice",
    purpose: "Classify notices, bind due dates, draft responses, collect attachments, request approval, and retain receipt evidence.",
    domain: "compliance",
    states: { order: ["received", "classification", "response_draft", "approval_pending", "submitted", "receipt_recorded", "closed"] },
    transitions: {
      received: ["classification"],
      classification: ["response_draft", "blocked"],
      response_draft: ["approval_pending"],
      approval_pending: ["submitted", "rejected"],
      submitted: ["receipt_recorded"],
      receipt_recorded: ["closed"],
    },
    objects: { required: ["obligation", "filing_draft", "document", "evidence_packet"] },
    approvals: { required: ["agency_response_approval"], states: { approval_pending: ["agency_response_approval"] } },
    evidence: { packet: "notice_packet" },
    tests: { required: ["due_date_present", "response_draft_present", "submission_blocked_until_approval"] },
    objectIdKey: "obligationObject",
    runState: "classification",
    runData: { noticeType: "payroll_tax", dueDateRequired: true },
    blockers: ["notice_due_date_required", "source_scan_required"],
    metrics: { readiness: 0.25 },
    stepName: "Agency notice seeded classification",
    stepOutput: { blockers: ["notice_due_date_required", "source_scan_required"] },
  },
];
