import { describe, expect, it } from "vitest";

import { summarizeCoreReadiness, type CoreSummary } from "./summary";

const emptySummary: CoreSummary = {
  tenantName: null,
  counts: {
    tenants: 0,
    legalEntities: 0,
    people: 0,
    employments: 0,
    compensationAgreements: 0,
    paySchedules: 0,
    payrollRuns: 0,
    rulePacks: 0,
    obligations: 0,
    filingRequirements: 0,
    filingDrafts: 0,
    bankAccounts: 0,
    paymentInstructions: 0,
    workflowDefinitions: 0,
    workflowRuns: 0,
    workerRuns: 0,
    approvalRequests: 0,
    auditEvents: 0,
    objects: 0,
    objectLinks: 0,
    objectVersions: 0,
    documents: 0,
    decisions: 0,
    evaluations: 0,
    entityIdentifiers: 0,
    customers: 0,
    leads: 0,
    offers: 0,
    quotes: 0,
    jobs: 0,
    invoices: 0,
    payments: 0,
    tasks: 0,
    evidence: 0,
    events: 0,
    capabilities: 0,
    capabilityGrants: 0,
    workers: 0,
    modelProviders: 0,
    modelRoutes: 0,
    budgetPolicies: 0,
    budgetPools: 0,
    budgetAccounts: 0,
    budgetAllocations: 0,
    budgetReservations: 0,
    usageEvents: 0,
    generatedViews: 0,
    adapters: 0,
    connections: 0,
    adapterRuns: 0,
    adapterActions: 0,
    inferences: 0,
  },
  activeTasks: [],
  recentEvents: [],
};

describe("summarizeCoreReadiness", () => {
  it("reports readiness from persisted primitive counts", () => {
    expect(
      summarizeCoreReadiness({
        ...emptySummary,
        counts: {
          ...emptySummary.counts,
          tenants: 1,
          objects: 2,
          objectVersions: 1,
          customers: 1,
          leads: 1,
          tasks: 2,
          capabilities: 3,
          evidence: 1,
          budgetPolicies: 1,
          budgetAllocations: 1,
          budgetAccounts: 1,
          modelProviders: 1,
          modelRoutes: 1,
          adapters: 1,
          connections: 1,
          legalEntities: 1,
          bankAccounts: 1,
          people: 1,
          employments: 1,
          paySchedules: 1,
          payrollRuns: 1,
          rulePacks: 1,
          obligations: 1,
          filingRequirements: 1,
          filingDrafts: 1,
          workflowDefinitions: 1,
          workflowRuns: 1,
          workerRuns: 1,
          approvalRequests: 1,
          auditEvents: 1,
          documents: 1,
          evaluations: 1,
        },
      }),
    ).toEqual({
      hasTenant: true,
      hasGraph: true,
      hasObjectSpine: true,
      hasTaskLedger: true,
      hasCapabilities: true,
      hasEvidence: true,
      hasBudgets: true,
      hasAiGateway: true,
      hasAdapterLedger: true,
      hasEntity: true,
      hasWorkforce: true,
      hasPayroll: true,
      hasCompliance: true,
      hasFilings: true,
      hasWorkflows: true,
      hasWorkerRuns: true,
      hasAuthority: true,
      hasDocuments: true,
      hasEvaluations: true,
    });
  });
});
